# Generated by Django 6.1.1 on 2026-09-06 19:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Canonical registration number, e.g. UMA123AA', max_length=32)),
                ('plate_serial', models.CharField(blank=True, max_length=64)),
                ('tracker_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Installation Evidence'), ('MATCHED', 'Matched to Evidence'), ('SUBMITTED', 'Submitted to ITMS'), ('FAILED', 'Submission Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the file contents, used for deduplication.', max_length=64, unique=True)),
                ('original_source_path', models.CharField(max_length=1024)),
                ('vault_file', models.CharField(help_text='Path (relative to MEDIA_ROOT) of the immutable vault copy.', max_length=1024)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('detected_plate', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('detector_confidence', models.FloatField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, help_text='Plate bounding box as [x1, y1, x2, y2] in pixel coordinates.', null=True)),
                ('orientation', models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('orientation_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New / Not Processed'), ('PROCESSING', 'Processing'), ('PLATE_DETECTED', 'Plate Detected'), ('MATCHED', 'Matched to Order'), ('INCOMPLETE', 'Incomplete Pair'), ('NEEDS_REVIEW', 'Needs Operator Review'), ('READY', 'Ready for Submission'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('DUPLICATE_SKIPPED', 'Duplicate Skipped')], default='NEW', max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['detected_plate', 'orientation'], name='core_eviden_detecte_7c631a_idx'), models.Index(fields=['status'], name='core_eviden_status_b8062b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleInstallationPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number_detected', models.CharField(db_index=True, help_text='Canonical plate string this pair was grouped under.', max_length=32)),
                ('verification_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('INCOMPLETE', 'Incomplete'), ('CONFLICT', 'Conflict'), ('UNREGISTERED', 'Unregistered Vehicle'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Submission Failed')], default='PENDING_REVIEW', max_length=20)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('FUZZY', 'Fuzzy Match'), ('NONE', 'No Match')], default='NONE', max_length=8)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('operator_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('front_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_front_of', to='core.evidenceimage')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairs', to='core.installationorder')),
                ('rear_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_rear_of', to='core.evidenceimage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('FALLBACK', 'Manual Fallback Triggered')], max_length=24)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('INFO', 'Info')], max_length=8)),
                ('message', models.TextField(blank=True)),
                ('simulated_token', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.vehicleinstallationpair')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
