# Generated by Django 5.2.17 on 2026-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceimage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times vision processing has been attempted on this image.'),
        ),
    ]
