# Generated by Django 5.2.17 on 2026-09-07 01:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_retry_count_to_evidenceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, help_text='Human-readable batch identifier, e.g. BATCH-20260907-142030-ab12', max_length=64, unique=True)),
                ('source_type', models.CharField(choices=[('CLI', 'Command Line Ingestion'), ('WEB', 'Web Upload'), ('API', 'REST API')], default='CLI', max_length=16)),
                ('source_label', models.CharField(blank=True, help_text='Folder name, operator name, or upload note for this batch.', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('ingested_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ingestion batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='is_file_pruned',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the heavy vault file has been pruned per the 7-day retention policy.'),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='pruned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this evidence was successfully submitted to ITMS.', null=True),
        ),
        migrations.AddField(
            model_name='vehicleinstallationpair',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this pair was successfully submitted to ITMS.', null=True),
        ),
        migrations.AlterField(
            model_name='evidenceimage',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Not Processed'), ('PROCESSING', 'Processing'), ('PLATE_DETECTED', 'Plate Detected'), ('MATCHED', 'Matched to Order'), ('INCOMPLETE', 'Incomplete Pair'), ('NEEDS_REVIEW', 'Needs Operator Review'), ('READY', 'Ready for Submission'), ('SUBMITTED', 'Submitted'), ('PRUNED', 'Pruned (Retention Policy)'), ('FAILED', 'Failed'), ('DUPLICATE_SKIPPED', 'Duplicate Skipped')], default='NEW', max_length=24),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The ingestion batch this image was uploaded in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.ingestionbatch'),
        ),
        migrations.AddIndex(
            model_name='evidenceimage',
            index=models.Index(fields=['status', 'submitted_at'], name='core_eviden_status_4cc32d_idx'),
        ),
    ]
