# Generated by Django 5.2.17 on 2026-09-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingestionbatch_evidenceimage_is_file_pruned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceimage',
            name='captured_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='EXIF capture timestamp (DateTimeOriginal).', null=True),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='folder_orientation',
            field=models.CharField(blank=True, help_text='Orientation inferred from folder structure (FRONT or REAR).', max_length=16),
        ),
    ]
