# Generated by Django 5.2.17 on 2026-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evidenceimage_captured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationorder',
            name='installation_date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='installation_officer',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='True if order is in /installation-orders/archive'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='itms_action_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='itms_order_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='old_registration_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='order_status',
            field=models.CharField(blank=True, default='', help_text='e.g. Under installation, Ready for approve, Installed', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='registration_status',
            field=models.CharField(blank=True, default='', help_text='e.g. Active', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='sales_order',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='warehouse_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='installationorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Installation Evidence'), ('MATCHED', 'Matched to Evidence'), ('SUBMITTED', 'Submitted to ITMS'), ('INSTALLED', 'Installed (Verified in Archive)'), ('FAILED', 'Submission Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
