# Generated by Django 5.2.17 on 2026-09-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_installationorder_installation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionauditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('ARCHIVE_VERIFY', 'Archive Installation Verification'), ('FALLBACK', 'Manual Fallback Triggered')], max_length=24),
        ),
    ]
