# Generated by Django 5.2.17 on 2026-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_submissionauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationorder',
            name='details_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='front_beacon_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='front_photo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='front_plate_serial',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='front_plate_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='gps_tracker_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='info_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='photos_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='rear_beacon_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='rear_photo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='rear_plate_serial',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='rear_plate_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='submissionauditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('ARCHIVE_VERIFY', 'Archive Installation Verification'), ('ORDER_INFO_FETCH', 'Order Info Inspection'), ('PHOTO_DOWNLOAD', 'ITMS Photo Download'), ('FALLBACK', 'Manual Fallback Triggered')], max_length=24),
        ),
    ]
