# Generated by Django 5.2.17 on 2026-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_installationorder_details_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceimage',
            name='order_guided_plate',
            field=models.CharField(blank=True, default='', help_text='Plate candidate resolved via active ITMS order prior matching.', max_length=32),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='raw_ocr_text',
            field=models.CharField(blank=True, default='', help_text='Raw unnormalized OCR character string from engine before normalizer or order guidance.', max_length=64),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='has_front_photo',
            field=models.BooleanField(default=False, help_text='True if front photo is confirmed present on ITMS'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='has_rear_photo',
            field=models.BooleanField(default=False, help_text='True if rear photo is confirmed present on ITMS'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='is_active_on_itms',
            field=models.BooleanField(db_index=True, default=True, help_text='True if order is currently active on ITMS /installation-orders/index'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='itms_stage',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Current stage on ITMS (STAGE_1_INSTALLATION, STAGE_2_APPROVE, STAGE_3_CONFIRMATION, ARCHIVED)', max_length=32),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when order was last verified or synced with ITMS', null=True),
        ),
        migrations.AddField(
            model_name='vehicleinstallationpair',
            name='is_manual_override',
            field=models.BooleanField(db_index=True, default=False, help_text='True if operator manually typed or confirmed the plate / order identity.'),
        ),
        migrations.AddField(
            model_name='vehicleinstallationpair',
            name='manual_plate_override',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='vehicleinstallationpair',
            name='matched_via',
            field=models.CharField(choices=[('VISION', 'Vision OCR'), ('ORDER_PRIOR', 'Order Prior Guided'), ('MANUAL', 'Manual Operator Entry'), ('REPAIR', 'Manual Re-Pair')], default='VISION', help_text='Pipeline stage that determined the pair grouping and plate identity.', max_length=16),
        ),
        migrations.AlterField(
            model_name='submissionauditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('ARCHIVE_VERIFY', 'Archive Installation Verification'), ('ORDER_INFO_FETCH', 'Order Info Inspection'), ('PHOTO_DOWNLOAD', 'ITMS Photo Download'), ('ORDER_SYNC', 'Order Registry Sync'), ('MANUAL_PLATE_ASSIGN', 'Manual Plate Assignment'), ('ORDER_PRIOR_CORRECT', 'Order Prior Hypothesis Correction'), ('FALLBACK', 'Manual Fallback Triggered')], max_length=32),
        ),
    ]
