# Generated by Django 5.2.17 on 2026-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evidenceimage_order_guided_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='account_email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Active ITMS account email at time of ingestion.', max_length=255),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='account_email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ITMS account email that fetched/owns this order.', max_length=255),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='account_uuid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ITMS account UUID that fetched/owns this order.', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicleinstallationpair',
            name='account_email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ITMS account email associated with this pair.', max_length=255),
        ),
    ]
