# Generated by Django 5.2.17 on 2026-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ingestionbatch_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionauditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('ARCHIVE_VERIFY', 'Archive Installation Verification'), ('ORDER_INFO_FETCH', 'Order Info Inspection'), ('PHOTO_DOWNLOAD', 'ITMS Photo Download'), ('ORDER_SYNC', 'Order Registry Sync'), ('MANUAL_PLATE_ASSIGN', 'Manual Plate Assignment'), ('ORDER_PRIOR_CORRECT', 'Order Prior Hypothesis Correction'), ('OUTBOX_QUEUE', 'Offline Outbox Queued'), ('OUTBOX_DRAIN', 'Offline Outbox Auto-Synced'), ('FALLBACK', 'Manual Fallback Triggered')], max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('INCOMPLETE', 'Incomplete'), ('CONFLICT', 'Conflict'), ('UNREGISTERED', 'Unregistered Vehicle'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Submission Failed'), ('OFFLINE_OUTBOX', 'Offline Outbox')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
