# Generated by Django 5.2.17 on 2026-09-19 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_submissionauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceimage',
            name='preview_file',
            field=models.CharField(blank=True, default='', help_text='Path (relative to MEDIA_ROOT) of 640x480 WebP preview.', max_length=1024),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='thumbnail_file',
            field=models.CharField(blank=True, default='', help_text='Path (relative to MEDIA_ROOT) of 160x120 WebP thumbnail.', max_length=1024),
        ),
        migrations.AddField(
            model_name='submissionauditlog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionauditlog',
            name='operator_username',
            field=models.CharField(blank=True, default='System', max_length=150),
        ),
        migrations.AlterField(
            model_name='submissionauditlog',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.vehicleinstallationpair'),
        ),
    ]
