# Generated by Django on 2026-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_evidenceimage_preview_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionbatch',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('CLI', 'Command Line Ingestion'),
                    ('WEB', 'Web Upload'),
                    ('API', 'REST API'),
                    ('MOBILE', 'Mobile Direct Capture'),
                ],
                default='CLI',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='matched_via',
            field=models.CharField(
                choices=[
                    ('VISION', 'Vision OCR'),
                    ('ORDER_PRIOR', 'Order Prior Guided'),
                    ('MANUAL', 'Manual Operator Entry'),
                    ('REPAIR', 'Manual Re-Pair'),
                    ('MOBILE_CONVEYOR', 'Mobile Conveyor Direct Pair'),
                ],
                default='VISION',
                help_text='Pipeline stage that determined the pair grouping and plate identity.',
                max_length=16,
            ),
        ),
    ]
