# Generated by Django 5.2.17 on 2026-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ingestionbatch_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_code', models.CharField(db_index=True, help_text='e.g. IK-UMA300PW', max_length=64, unique=True)),
                ('registration_number', models.CharField(db_index=True, help_text='e.g. UMA 300PW', max_length=32)),
                ('front_plate', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rear_plate', models.CharField(blank=True, db_index=True, max_length=64)),
                ('front_tracker', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rear_tracker', models.CharField(blank=True, db_index=True, max_length=64)),
                ('gps_tracker', models.CharField(blank=True, db_index=True, max_length=64)),
                ('warehouse', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, default='New', max_length=64)),
                ('created_date', models.CharField(blank=True, default='', max_length=64)),
                ('kit_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('detail_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_user', models.CharField(blank=True, default='', max_length=128)),
                ('front_plate_article', models.CharField(blank=True, default='', max_length=64)),
                ('rear_plate_article', models.CharField(blank=True, default='', max_length=64)),
                ('gps_article', models.CharField(blank=True, default='', max_length=64)),
                ('sim_article', models.CharField(blank=True, default='', max_length=64)),
                ('sim_serial', models.CharField(blank=True, default='', max_length=64)),
                ('sim_mac', models.CharField(blank=True, default='', max_length=64)),
                ('front_tracker_article', models.CharField(blank=True, default='', max_length=64)),
                ('rear_tracker_article', models.CharField(blank=True, default='', max_length=64)),
                ('front_tracker_mac', models.CharField(blank=True, default='', max_length=64)),
                ('rear_tracker_mac', models.CharField(blank=True, default='', max_length=64)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
