# Generated by Django 5.2.17 on 2026-09-29 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_installationkit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, unique=True)),
                ('work_date_suffix', models.CharField(db_index=True, max_length=16)),
                ('warehouse_name', models.CharField(blank=True, default='Warehouse Stock', max_length=128)),
                ('opening_stock', models.IntegerField(default=0, help_text='Stock at start of shift')),
                ('delivered_count', models.IntegerField(default=0, help_text='Total plates received in deliveries')),
                ('dispatched_count', models.IntegerField(default=0, help_text='Total plates taken out to line')),
                ('installed_count', models.IntegerField(default=0, help_text='Plates verified installed in archive')),
                ('pending_count', models.IntegerField(default=0, help_text='Plates active in orders')),
                ('returned_count', models.IntegerField(default=0, help_text='Plates returned uninstalled to stock')),
                ('unallocated_count', models.IntegerField(default=0, help_text='Discrepancy: Dispatched - Returned - Installed - Pending')),
                ('closing_stock', models.IntegerField(default=0, help_text='Calculated closing stock balance')),
                ('physical_count', models.IntegerField(blank=True, help_text='Optional manual physical count audit', null=True)),
                ('variance', models.IntegerField(default=0, help_text='Variance between physical count and closing stock')),
                ('is_closed', models.BooleanField(default=False, help_text='True if shift stock has been locked/closed')),
                ('notes', models.TextField(blank=True, default='')),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily stock ledgers',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='StockDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(db_index=True, help_text='Delivery manifest or shipment reference, e.g. DEL-20260929-01', max_length=64, unique=True)),
                ('supplier', models.CharField(blank=True, default='Factory / Central Depot', help_text='Origin supplier, factory or dispatching depot', max_length=128)),
                ('delivery_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('target_date_suffix', models.CharField(blank=True, db_index=True, help_text='6-digit date suffix matching shift orders, e.g. 260926', max_length=16)),
                ('total_plates_count', models.PositiveIntegerField(default=0)),
                ('operator_name', models.CharField(blank=True, default='Operator', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock deliveries',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=32)),
                ('plate_serial', models.CharField(blank=True, default='', max_length=64)),
                ('kit_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stockdelivery')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockDispatchScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=32)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('work_date_suffix', models.CharField(db_index=True, help_text='6-digit date suffix, e.g. 260926', max_length=16)),
                ('dispatched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operator_name', models.CharField(blank=True, default='Operator', max_length=150)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched to Line'), ('INSTALLED', 'Installed (Archived)'), ('PENDING_ORDER', 'Pending in Order'), ('RETURNED', 'Returned to Stock'), ('UNALLOCATED', 'Unallocated / Missing')], db_index=True, default='DISPATCHED', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock dispatch scans',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReturnScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=32)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('work_date_suffix', models.CharField(db_index=True, help_text='6-digit date suffix, e.g. 260926', max_length=16)),
                ('returned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operator_name', models.CharField(blank=True, default='Operator', max_length=150)),
                ('reason', models.CharField(choices=[('BIKE_NO_SHOW', 'Motorcycle No-Show'), ('DEFECTIVE_PLATE', 'Defective Plate / Hardware'), ('CANCELLED_ORDER', 'Cancelled Order'), ('LINE_ROLLOVER', 'End of Shift Line Return'), ('OTHER', 'Other')], default='BIKE_NO_SHOW', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock return scans',
                'ordering': ['-returned_at'],
            },
        ),
    ]
