# Generated by Django 5.2.17 on 2026-09-29 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailystockledger_stockdelivery_stockdeliveryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBondTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(db_index=True, help_text='Transfer reference e.g. TRF-IN-20260929-01', max_length=64, unique=True)),
                ('transfer_type', models.CharField(choices=[('TRANSFER_IN', 'Bond Transfer In (Received from another bond)'), ('TRANSFER_OUT', 'Bond Transfer Out (Sent to another bond)')], db_index=True, max_length=16)),
                ('plate_category', models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', help_text='PSV (Public White) or PMO (Private Yellow)', max_length=8)),
                ('other_bond_name', models.CharField(blank=True, default='Other Bond', help_text='Name of external bond transferred to/from', max_length=128)),
                ('transfer_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('target_date_suffix', models.CharField(blank=True, db_index=True, max_length=16)),
                ('plates_count', models.PositiveIntegerField(default=0)),
                ('operator_name', models.CharField(blank=True, default='Operator', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stock bond transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_in_pmo',
            field=models.IntegerField(default=0, help_text='PMO kits transferred into our bond from other bonds'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_in_psv',
            field=models.IntegerField(default=0, help_text='PSV kits transferred into our bond from other bonds'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_in_total',
            field=models.IntegerField(default=0, help_text='Combined bond transfer in'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_out_pmo',
            field=models.IntegerField(default=0, help_text='PMO kits transferred out from our bond to other bonds'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_out_psv',
            field=models.IntegerField(default=0, help_text='PSV kits transferred out from our bond to other bonds'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='bond_transfer_out_total',
            field=models.IntegerField(default=0, help_text='Combined bond transfer out'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='closing_balance_pmo',
            field=models.IntegerField(default=0, help_text='PMO calculated closing stock balance'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='closing_balance_psv',
            field=models.IntegerField(default=0, help_text='PSV calculated closing stock balance'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='kits_installed_pmo',
            field=models.IntegerField(default=0, help_text='PMO kits installed in orders & archive for that day'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='kits_installed_psv',
            field=models.IntegerField(default=0, help_text='PSV kits installed in orders & archive for that day'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='kits_received_pmo',
            field=models.IntegerField(default=0, help_text='PMO kits received from supplier/central depot'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='kits_received_psv',
            field=models.IntegerField(default=0, help_text='PSV kits received from supplier/central depot'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='opening_balance_pmo',
            field=models.IntegerField(default=0, help_text='PMO stock at start of shift'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='opening_balance_psv',
            field=models.IntegerField(default=0, help_text='PSV stock at start of shift'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='scheduled_pmo',
            field=models.IntegerField(default=0, help_text='Target PMO plates scheduled for installation under the bond (manually entered)'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='scheduled_psv',
            field=models.IntegerField(default=0, help_text='Target PSV plates scheduled for installation under the bond (manually entered)'),
        ),
        migrations.AddField(
            model_name='dailystockledger',
            name='scheduled_total',
            field=models.IntegerField(default=0, help_text='Combined scheduled installation target'),
        ),
        migrations.AddField(
            model_name='stockdelivery',
            name='plate_category',
            field=models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', help_text='PSV (Public White) or PMO (Private Yellow)', max_length=8),
        ),
        migrations.AddField(
            model_name='stockdeliveryitem',
            name='plate_category',
            field=models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', max_length=8),
        ),
        migrations.AddField(
            model_name='stockdispatchscan',
            name='plate_category',
            field=models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', max_length=8),
        ),
        migrations.AddField(
            model_name='stockreturnscan',
            name='plate_category',
            field=models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', max_length=8),
        ),
        migrations.AlterField(
            model_name='dailystockledger',
            name='closing_stock',
            field=models.IntegerField(default=0, help_text='Combined calculated closing stock balance'),
        ),
        migrations.AlterField(
            model_name='dailystockledger',
            name='delivered_count',
            field=models.IntegerField(default=0, help_text='Combined kits received'),
        ),
        migrations.AlterField(
            model_name='dailystockledger',
            name='installed_count',
            field=models.IntegerField(default=0, help_text='Combined kits installed'),
        ),
        migrations.AlterField(
            model_name='dailystockledger',
            name='opening_stock',
            field=models.IntegerField(default=0, help_text='Combined opening stock'),
        ),
        migrations.AlterField(
            model_name='dailystockledger',
            name='warehouse_name',
            field=models.CharField(blank=True, default='Warehouse Stock / Bond', max_length=128),
        ),
    ]
