# Generated by Django 5.2.17 on 2026-09-29 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stockbondtransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdelivery',
            name='delivery_note_image',
            field=models.ForeignKey(blank=True, help_text='Optional photo of paper delivery note in Evidence Vault', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='core.evidenceimage'),
        ),
        migrations.AddField(
            model_name='stockdelivery',
            name='paper_note_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Printed physical delivery note number from paper slip', max_length=64),
        ),
        migrations.AlterField(
            model_name='stockdelivery',
            name='delivery_number',
            field=models.CharField(db_index=True, help_text='Delivery manifest or shipment reference, e.g. DN-20260930-01', max_length=64, unique=True),
        ),
    ]
