# Generated by Django 5.2.17 on 2026-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stockdelivery_delivery_note_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdispatchscan',
            name='bond_code',
            field=models.CharField(blank=True, db_index=True, default='AGM', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockdispatchscan',
            name='status',
            field=models.CharField(choices=[('RECONCILED_INSTALLED', 'Reconciled Installed (Archive)'), ('RETURNED_TO_SAFE', 'Returned to Safe Room'), ('ON_LINE_ACTIVE', 'On Line Active (Fitting in Progress)'), ('PENDING_SYSTEM_SYNC', 'Pending ITMS Sync (Local Queue)'), ('UNRESOLVED_DISCREPANCY', 'Unresolved Discrepancy (MVR Review)'), ('DISPATCHED', 'Dispatched to Line'), ('INSTALLED', 'Installed (Archived)'), ('PENDING_ORDER', 'Pending in Order'), ('RETURNED', 'Returned to Stock'), ('UNALLOCATED', 'Unallocated Discrepancy')], db_index=True, default='DISPATCHED', max_length=32),
        ),
    ]
