# Generated by Django 5.2.17 on 2026-10-02 19:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stockdispatchscan_bond_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceimage',
            name='ingested_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evidenceimage',
            name='orientation',
            field=models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.AlterField(
            model_name='installationorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='installationorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Installation Evidence'), ('MATCHED', 'Matched to Evidence'), ('SUBMITTED', 'Submitted to ITMS'), ('INSTALLED', 'Installed (Verified in Archive)'), ('FAILED', 'Submission Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='installationorder',
            name='warehouse_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='submissionauditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_LOOKUP', 'Order Lookup'), ('SERIAL_VERIFY', 'Serial Verification'), ('UPLOAD_FRONT', 'Front Photo Upload'), ('UPLOAD_REAR', 'Rear Photo Upload'), ('VALIDATE', 'Submission Validation'), ('SUBMIT', 'Final Submission'), ('OPERATOR_OVERRIDE', 'Operator Override'), ('OPERATOR_APPROVE', 'Operator Approve'), ('OPERATOR_SWAP', 'Operator Front/Rear Swap'), ('ARCHIVE_VERIFY', 'Archive Installation Verification'), ('ORDER_INFO_FETCH', 'Order Info Inspection'), ('PHOTO_DOWNLOAD', 'ITMS Photo Download'), ('ORDER_SYNC', 'Order Registry Sync'), ('MANUAL_PLATE_ASSIGN', 'Manual Plate Assignment'), ('ORDER_PRIOR_CORRECT', 'Order Prior Hypothesis Correction'), ('OUTBOX_QUEUE', 'Offline Outbox Queued'), ('OUTBOX_DRAIN', 'Offline Outbox Auto-Synced'), ('FALLBACK', 'Manual Fallback Triggered')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='submissionauditlog',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('INFO', 'Info')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicleinstallationpair',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('INCOMPLETE', 'Incomplete'), ('CONFLICT', 'Conflict'), ('UNREGISTERED', 'Unregistered Vehicle'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Submission Failed'), ('OFFLINE_OUTBOX', 'Offline Outbox')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AddIndex(
            model_name='evidenceimage',
            index=models.Index(fields=['batch', 'orientation'], name='core_eviden_batch_i_098d23_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceimage',
            index=models.Index(fields=['batch', 'status'], name='core_eviden_batch_i_2a17b3_idx'),
        ),
        migrations.AddIndex(
            model_name='installationorder',
            index=models.Index(fields=['status', '-created_at'], name='core_instal_status_b69184_idx'),
        ),
        migrations.AddIndex(
            model_name='installationorder',
            index=models.Index(fields=['registration_number', 'status'], name='core_instal_registr_e1beb1_idx'),
        ),
        migrations.AddIndex(
            model_name='installationorder',
            index=models.Index(fields=['is_active_on_itms', 'is_archived'], name='core_instal_is_acti_eff96b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdeliveryitem',
            index=models.Index(fields=['delivery', 'registration_number'], name='core_stockd_deliver_40661b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdispatchscan',
            index=models.Index(fields=['work_date', 'status'], name='core_stockd_work_da_51532d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdispatchscan',
            index=models.Index(fields=['work_date_suffix', 'status'], name='core_stockd_work_da_ce8657_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreturnscan',
            index=models.Index(fields=['work_date', 'reason'], name='core_stockr_work_da_d5f585_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreturnscan',
            index=models.Index(fields=['work_date_suffix', 'reason'], name='core_stockr_work_da_6a3ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionauditlog',
            index=models.Index(fields=['pair', 'action', '-timestamp'], name='core_submis_pair_id_396d43_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_submis_action_970d14_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinstallationpair',
            index=models.Index(fields=['verification_status', 'is_complete'], name='core_vehicl_verific_e2183e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinstallationpair',
            index=models.Index(fields=['verification_status', '-updated_at'], name='core_vehicl_verific_11433f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinstallationpair',
            index=models.Index(fields=['registration_number_detected', 'verification_status'], name='core_vehicl_registr_6b0358_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinstallationpair',
            index=models.Index(fields=['-updated_at'], name='core_vehicl_updated_a0ad10_idx'),
        ),
    ]
