# Generated by Django 5.2.17 on 2026-10-04 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_evidenceimage_ingested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeAuditScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=32)),
                ('plate_category', models.CharField(choices=[('PSV', 'Public White (PSV)'), ('PMO', 'Private Yellow (PMO)')], db_index=True, default='PSV', max_length=8)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('work_date_suffix', models.CharField(db_index=True, help_text='6-digit date suffix, e.g. 260926', max_length=16)),
                ('bond_code', models.CharField(blank=True, db_index=True, default='AGM', max_length=32)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operator_name', models.CharField(blank=True, default='Operator', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_audit_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Safe audit scans',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['work_date_suffix', 'registration_number'], name='core_safeau_work_da_9d9ef4_idx'), models.Index(fields=['work_date', 'plate_category'], name='core_safeau_work_da_2e6f82_idx')],
            },
        ),
    ]
