# Generated by Django 5.2.17 on 2026-10-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_safeauditscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorITMSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='https://stock.itms.ug', max_length=255)),
                ('itms_email', models.CharField(blank=True, default='', max_length=255)),
                ('itms_user_uuid', models.CharField(blank=True, default='', max_length=128)),
                ('itms_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('csrf_token', models.TextField(blank=True, default='')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_message', models.CharField(blank=True, default='', max_length=500)),
                ('active_bond_code', models.CharField(default='AGM', max_length=64)),
                ('active_bond_name', models.CharField(default='AGM Bonded Warehouse', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itms_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator ITMS Session',
                'verbose_name_plural': 'Operator ITMS Sessions',
            },
        ),
    ]
