#!/usr/bin/env python3
"""
ITMS Verification Copilot - Self-Healing Bootstrap & Resource Manager.
Cross-platform provisioning for Windows, macOS (Intel & Apple Silicon), and Linux.

Tasks Performed:
1. Validates and initializes `.env` with a secure random Django SECRET_KEY.
2. Ensures all required runtime directories exist (`media/vault`, `media/crops`, `secure/auth`, `exports`, `models`).
3. Verifies or automatically downloads fine-tuned plate detection weights (`license-plate-finetune-v1n.pt`, `license-plate-finetune-v1s.pt`).
4. Detects and configures the optimal OCR engine for the host OS (Tesseract / PaddleOCR).
5. Applies database schema migrations (`manage.py migrate`).
6. Ensures default operator account credentials are created if no users exist.
7. Supports `--verify-only` for non-destructive system health diagnostics.
"""
import argparse
import os
import platform
import secrets
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path
from typing import Optional, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Model weights URLs
MODEL_URLS = {
    "license-plate-finetune-v1n.pt": "https://huggingface.co/morsetechlab/yolov11-license-plate-detection/resolve/main/license-plate-finetune-v1n.pt",
    "license-plate-finetune-v1s.pt": "https://huggingface.co/morsetechlab/yolov11-license-plate-detection/resolve/main/license-plate-finetune-v1s.pt",
}

# Tesseract-OCR installer URL for Windows automated provisioning
TESSERACT_WINDOWS_URL = "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.4.0.20240606.exe"

# Required runtime directories
REQUIRED_DIRS = [
    PROJECT_ROOT / "media" / "vault",
    PROJECT_ROOT / "media" / "crops",
    PROJECT_ROOT / "secure" / "auth",
    PROJECT_ROOT / "exports",
    PROJECT_ROOT / "models",
]


def log_step(msg: str) -> None:
    print(f"  [>] {msg}")


def log_success(msg: str) -> None:
    print(f"  [\033[92m+\033[0m] {msg}")


def log_warning(msg: str) -> None:
    print(f"  [\033[93m!\033[0m] {msg}")


def log_error(msg: str) -> None:
    print(f"  [\033[91mx\033[0m] {msg}")


def ensure_directories() -> bool:
    """Creates all required runtime directories if missing."""
    log_step("Checking required directory structure...")
    for d in REQUIRED_DIRS:
        d.mkdir(parents=True, exist_ok=True)
    log_success("Runtime directories verified.")
    return True


def ensure_env_file() -> bool:
    """Ensures .env exists; copies from .env.example with generated SECRET_KEY if missing."""
    env_file = PROJECT_ROOT / ".env"
    env_example = PROJECT_ROOT / ".env.example"

    if env_file.is_file():
        log_success(".env configuration file found.")
        return True

    log_step("No .env found. Initializing from .env.example...")
    secret_key = secrets.token_urlsafe(50)

    if env_example.is_file():
        content = env_example.read_text(encoding="utf-8")
        content = content.replace("change-me-to-a-random-50-char-string", secret_key)
        # Ensure SQLite default
        if "POSTGRES_DB" in content:
            content = content.replace("POSTGRES_DB=num", "POSTGRES_DB=itms")
    else:
        content = f"""# Auto-generated by bootstrap.py
DJANGO_SECRET_KEY={secret_key}
DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
MEDIA_ROOT=media
VAULT_SUBDIR=vault
PLATE_YOLO_WEIGHTS=models/license-plate-finetune-v1n.pt
PLATE_DETECTOR_CONF_THRESHOLD=0.35
OCR_MIN_CONFIDENCE=0.55
USE_PADDLEOCR=True
ITMS_SUBMISSION_BACKEND=mock
ITMS_API_BASE_URL=https://stock.itms.ug
"""

    env_file.write_text(content, encoding="utf-8")
    log_success("Created .env with cryptographically secure DJANGO_SECRET_KEY.")
    return True


def download_file_with_progress(url: str, dest_path: Path) -> bool:
    """Downloads a file with clean progress indicators."""
    print(f"      Downloading {dest_path.name} from {url}...")
    temp_path = dest_path.with_suffix(".tmp")
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "ITMS-Verification-Copilot/1.0"},
        )
        with urllib.request.urlopen(req, timeout=30) as response, open(temp_path, "wb") as out_file:
            total_size = int(response.info().get("Content-Length", 0))
            downloaded = 0
            chunk_size = 65536

            while True:
                chunk = response.read(chunk_size)
                if not chunk:
                    break
                out_file.write(chunk)
                downloaded += len(chunk)
                if total_size > 0:
                    pct = (downloaded / total_size) * 100
                    mb_cur = downloaded / (1024 * 1024)
                    mb_tot = total_size / (1024 * 1024)
                    print(f"\r      [{pct:5.1f}%] {mb_cur:5.1f} MB / {mb_tot:5.1f} MB", end="", flush=True)

        print()
        temp_path.replace(dest_path)
        log_success(f"Saved {dest_path.name} ({dest_path.stat().st_size // 1024} KB).")
        return True
    except Exception as exc:
        print()
        log_warning(f"Download failed for {dest_path.name}: {exc}")
        if temp_path.exists():
            temp_path.unlink()
        return False


def ensure_model_weights(download_missing: bool = True) -> bool:
    """Checks for required fine-tuned license plate detection weights (v1n and v1s)."""
    log_step("Verifying fine-tuned plate detection model weights...")
    models_dir = PROJECT_ROOT / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    v1n_path = models_dir / "license-plate-finetune-v1n.pt"
    v1s_path = models_dir / "license-plate-finetune-v1s.pt"

    has_v1n = v1n_path.is_file()
    has_v1s = v1s_path.is_file()

    if has_v1n and has_v1s:
        log_success("Fine-tuned plate models verified (license-plate-finetune-v1n.pt, license-plate-finetune-v1s.pt).")
        return True

    if not download_missing:
        log_warning(f"Missing fine-tuned plate weights: v1n={has_v1n}, v1s={has_v1s}")
        return has_v1n or has_v1s

    # Download missing fine-tuned plate weights
    if not has_v1n:
        download_file_with_progress(MODEL_URLS["license-plate-finetune-v1n.pt"], v1n_path)

    if not has_v1s:
        download_file_with_progress(MODEL_URLS["license-plate-finetune-v1s.pt"], v1s_path)

    return v1n_path.is_file() or v1s_path.is_file()


def ensure_tesseract_installed(download_missing: bool = True) -> Tuple[bool, Optional[str]]:
    """
    Checks for Tesseract-OCR binary.
    If missing on Windows and download_missing=True:
    1. Attempts silent install via winget.
    2. If winget fails or is absent, downloads UB-Mannheim installer and runs silent install into tools/tesseract.
    """
    project_tools_tesseract = PROJECT_ROOT / "tools" / "tesseract" / "tesseract.exe"

    check_paths = [
        project_tools_tesseract,
        Path(r"C:\Program Files\Tesseract-OCR\tesseract.exe"),
        Path(r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"),
        Path("/opt/homebrew/bin/tesseract"),
        Path("/usr/local/bin/tesseract"),
        Path("/usr/bin/tesseract"),
    ]
    for p in check_paths:
        if p.is_file():
            try:
                probe = subprocess.run([str(p), "--version"], capture_output=True, timeout=5)
                if probe.returncode == 0:
                    return True, str(p)
            except Exception:
                continue

    shutil_which = shutil.which("tesseract")
    if shutil_which:
        try:
            probe = subprocess.run([shutil_which, "--version"], capture_output=True, timeout=5)
            if probe.returncode == 0:
                return True, shutil_which
        except Exception:
            pass

    if not download_missing or platform.system().lower() != "windows":
        return False, None

    log_warning("Tesseract-OCR was not detected. Initializing automated zero-configuration provisioning...")

    # Strategy 1: Attempt winget if available
    winget_bin = shutil.which("winget")
    if winget_bin:
        try:
            log_step("Attempting Tesseract installation via Windows Package Manager (winget)...")
            subprocess.run(
                [winget_bin, "install", "UB-Mannheim.TesseractOCR", "--silent", "--accept-package-agreements", "--accept-source-agreements"],
                capture_output=True,
                text=True,
                timeout=180,
            )
            standard_path = Path(r"C:\Program Files\Tesseract-OCR\tesseract.exe")
            if standard_path.is_file():
                log_success(f"Tesseract installed successfully via winget ({standard_path}).")
                return True, str(standard_path)
        except Exception as exc:
            log_warning(f"winget execution failed or unavailable: {exc}")

    # Strategy 2: Direct download of UB-Mannheim installer and silent local installation into tools/tesseract
    log_step("winget unavailable or failed. Downloading official UB-Mannheim Tesseract 5.4 installer...")
    temp_dir = Path(tempfile.gettempdir())
    installer_path = temp_dir / "tesseract-ocr-setup.exe"
    dest_tools_dir = PROJECT_ROOT / "tools" / "tesseract"
    dest_tools_dir.mkdir(parents=True, exist_ok=True)

    downloaded = download_file_with_progress(TESSERACT_WINDOWS_URL, installer_path)
    if downloaded and installer_path.is_file():
        try:
            log_step(f"Running silent local installation into {dest_tools_dir} (user-level, no admin required)...")
            # NSIS installer /S runs silent, /D= specifies destination directory (without quotes)
            install_cmd = f'"{installer_path}" /S /D={dest_tools_dir}'
            subprocess.run(install_cmd, shell=True, timeout=120)

            # Allow filesystem a moment to flush files
            import time
            time.sleep(3)

            if project_tools_tesseract.is_file():
                log_success(f"Tesseract successfully provisioned locally: {project_tools_tesseract}")
                return True, str(project_tools_tesseract)
            else:
                log_warning(f"Installer completed but {project_tools_tesseract} was not found.")
        except Exception as exc:
            log_error(f"Failed running Tesseract installer: {exc}")
        finally:
            if installer_path.is_file():
                try:
                    installer_path.unlink()
                except Exception:
                    pass

    return False, None


def detect_and_configure_ocr(download_missing: bool = True) -> dict:
    """Detects available OCR engines and configures settings for the host OS."""
    log_step("Diagnosing OCR engine and platform compatibility...")
    host_os = platform.system().lower()
    machine = platform.machine().lower()
    py_ver = sys.version_info

    # 1. Check or automatically provision Tesseract
    tesseract_found, tesseract_path = ensure_tesseract_installed(download_missing=download_missing)

    # 2. Check PaddleOCR capability
    paddle_usable = False
    try:
        import paddleocr  # noqa: F401
        paddle_usable = True
    except Exception:
        paddle_usable = False

    log_success(f"Host OS: {platform.system()} ({machine}) | Python: {py_ver.major}.{py_ver.minor}")
    if paddle_usable:
        log_success("PaddleOCR Engine: Available (High accuracy).")
    else:
        log_step("PaddleOCR Engine: Not loaded (Using Tesseract OCR).")

    if tesseract_found:
        log_success(f"Tesseract OCR: Found at {tesseract_path}")
    else:
        if host_os == "darwin":
            log_warning("Tesseract not found. On macOS, run: brew install tesseract")
        elif host_os == "windows":
            log_warning("Tesseract not found. To run offline, copy 'tesseract.exe' into 'tools\\tesseract\\'")
        else:
            log_warning("Tesseract not found. On Linux, run: sudo apt install tesseract-ocr")

    return {
        "os": host_os,
        "machine": machine,
        "tesseract_found": tesseract_found,
        "tesseract_path": tesseract_path,
        "paddle_usable": paddle_usable,
    }


def ensure_database_and_operator(verify_only: bool = False) -> bool:
    """Applies Django migrations and seeds default operator account if needed."""
    log_step("Checking database migrations and operator credentials...")
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "itms_project.settings")

    try:
        import django
        django.setup()
        from django.core.management import call_command
        from django.contrib.auth.models import User
        from core.services import config_service

        if verify_only:
            db_info = config_service.get_active_database_info()
            log_success(f"Database: {db_info.get('vendor', 'sqlite').upper()} ({db_info.get('name')})")
            user_count = User.objects.count()
            log_success(f"Registered Operators: {user_count}")
            return True

        # Apply migrations
        call_command("migrate", interactive=False)
        log_success("Database schema verified and migrations applied.")

        # Ensure default operator
        config_service.ensure_operator_accounts_synced()
        log_success("Operator account setup verified.")
        return True
    except Exception as exc:
        log_error(f"Database error: {exc}")
        return False


def run_diagnostics_table() -> None:
    """Prints a clean, formatted diagnostic table for the user."""
    print()
    print("=" * 65)
    print("  ITMS VERIFICATION COPILOT - SYSTEM HEALTH DIAGNOSTICS")
    print("=" * 65)

    ensure_directories()
    ensure_env_file()
    ensure_model_weights(download_missing=False)
    ocr_info = detect_and_configure_ocr(download_missing=False)
    ensure_database_and_operator(verify_only=True)

    print("=" * 65)
    print("  System status: READY FOR OPERATION")
    print("  Web Console URL: http://127.0.0.1:8000")
    print("=" * 65)
    print()


def main() -> int:
    parser = argparse.ArgumentParser(description="ITMS Verification Copilot Bootstrap & Resource Manager")
    parser.add_argument("--verify-only", action="store_true", help="Run diagnostics without mutating files or downloading")
    args = parser.parse_args()

    print()
    print("=" * 65)
    print("  ITMS VERIFICATION COPILOT - SYSTEM INITIALIZATION")
    print("=" * 65)

    if args.verify_only:
        run_diagnostics_table()
        return 0

    # 1. Directories
    ensure_directories()

    # 2. Environment file
    ensure_env_file()

    # 3. Model weights
    ensure_model_weights(download_missing=True)

    # 4. OCR
    detect_and_configure_ocr(download_missing=True)

    # 5. Database & Admin user
    ok = ensure_database_and_operator(verify_only=False)
    if not ok:
        log_error("Bootstrap completed with warnings. Check logs above.")
        return 1

    print("=" * 65)
    log_success("Bootstrap complete. System is ready to launch.")
    print("=" * 65)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
